spring:
  profiles:
    active: h2

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder : TRACE

#spring.mvc.hiddenmethod.filter.enabled=true