spring:
  profiles:
    active: h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:email}
    password: ${MAIL_PASSWORD:password}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  liquibase:
#    enabled: false
#    change-log: changelog.sql

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

page:
  size: 5



#  spring.mail.host=smtp.gmail.com
#  spring.mail.port=587
#  spring.mail.username=<login user to smtp server>
#  spring.mail.password=<login password to smtp server>
#  spring.mail.properties.mail.smtp.auth=true
#  spring.mail.properties.mail.smtp.starttls.enable=true