spring:
  profiles:
    active: h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: pashaavilv666@gmail.com
    password: ksbkcyfgxesifonm
    #    password: Pashaavilv162431
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

page:
  size: 5



#  spring.mail.host=smtp.gmail.com
#  spring.mail.port=587
#  spring.mail.username=<login user to smtp server>
#  spring.mail.password=<login password to smtp server>
#  spring.mail.properties.mail.smtp.auth=true
#  spring.mail.properties.mail.smtp.starttls.enable=true